export enum EnumClaimToken {
    USERNAME = 'userName',
    FIRSTNAME = 'firstName',
    LASTNAME = 'lastName',
    EMAIL = 'email',
    PHONENUMBER = 'phoneNumber',
    USERID = 'id'
};

export enum EnumLookupCodeGroups {
    TIPO_PAGO_PEAJE = 'TIPO DE PAGO PEAJE',
    ESTADO_EMPRESA = 'ESTADO EMPRESA',
    CONDICION_EMPRESA = 'CONDICION EMPRESA',
    TIPO_DOCUMENTO = 'TIPO DE DOC. IDENTIDAD',
    CLAIMS_PERMITIDOS = 'CLAIMS PERMITIDOS',
    TIPO_LICENCIA_CONDUCIR = 'TIPO DE LICENCIA DE CONDUCIR',
    CATEGORIA_VEHICULOS = 'CATEGORIA VEHICULOS',
    TIPO_DE_EMPRESA = 'TIPO DE EMPRESA',
    TIPO_DE_SERVICIO = 'TIPO DE SERVICIO',
};
