// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace Sicotyc.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20231126053935_DatabaseCreation")]
    partial class DatabaseCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.LookupCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LookupCodeId");

                    b.Property<DateTime>("CreateDtm")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("DeleteDtm")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOn");

                    b.Property<Guid>("LookupCodeGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LookupCodeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LookupCodeOrder")
                        .HasColumnType("int");

                    b.Property<string>("LookupCodeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("UpdateDtm")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastUpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("LookupCodeGroupId");

                    b.ToTable("LOOKUP_CODE", "SCT");
                });

            modelBuilder.Entity("Entities.Models.LookupCodeGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LookupCodeGroupId");

                    b.Property<DateTime>("CreateDtm")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("DeleteDtm")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("LookupCodeGroupName");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("UpdateDtm")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastUpdatedOn");

                    b.HasKey("Id");

                    b.ToTable("LOOKUP_CODE_GROUP", "SCT");
                });

            modelBuilder.Entity("Entities.Models.LookupCode", b =>
                {
                    b.HasOne("Entities.Models.LookupCodeGroup", "LookupCodeGroup")
                        .WithMany("LookupCodes")
                        .HasForeignKey("LookupCodeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LookupCodeGroup");
                });

            modelBuilder.Entity("Entities.Models.LookupCodeGroup", b =>
                {
                    b.Navigation("LookupCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
